/* eslint-disable import/extensions */
import "./player.js";
import "./slider.js";
import "./menu.js";
import "./container.js";
import "./style/main.css";
import "./assets/age.png";
import "./assets/icon.png";
import "./assets/logo.png";
import "./assets/fone02.png";
import "./assets/fone03.png";
import "./assets/play_icon.png";
import "./assets/Lieutenant-CBB.mp3";
import "./assets/gunShut.mp3";
import "./assets/gunReturn.mp3";
import "./assets/Lieutenant-CBB.m4a";
import "./assets/Fearmonger Battle Pass _ Caliber.mp4";
import "./assets/Caliber is available in Steam.mp4";
import "./assets/Property 1=volume-up-line.png";
import "./assets/Property 1=volume-mute-line.png";
import "./assets/Play & Pause.png";
import "./assets/Property 1=Play.png";
import "./assets/clearIcon.png";
